spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Ikernellsolutions
    username: fabrica
    password: fabrica2024*
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
